# Spring Data JPA
spring.datasource.url=jdbc:postgresql://192.168.99.100:5432/task_management
spring.datasource.username=skillbox
spring.datasource.password=skillbox
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=mySecretKey
jwt.expirationMs=3600000